version: '3'

services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            args:
                environment: dev
        volumes:
            - ./:/usr/src/app
            - "~/.composer.sh:/root/.composer.sh"
            - "~/.ssh:/root/.ssh-local:ro"
        networks:
            - lar_doctrine
        depends_on:
            - postgresdb
        environment:
            - LOCAL_ENV=1
            - COMPOSER_ALLOW_SUPERUSER=1
            - DATABASE_HOST=mysql
            - DATABASE_NAME=project
            - DATABASE_USER=developer
            - DATABASE_PASSWORD=password
            - PHP_IDE_CONFIG=serverName=docker

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
            args:
                environment: dev
        volumes:
            - ./:/usr/src/app
        ports:
            - "8820:80"
        networks:
            - lar_doctrine
        depends_on:
            - php-fpm

    postgresdb:
        image: postgres:latest
        ports:
            - "5810:5432"
        networks:
            - lar_doctrine
        environment:
            - POSTGRES_DB=project
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=password
        volumes:
            - postgres:/data/postgres

networks:
    lar_doctrine:
        external: true
volumes:
    postgres:
